#! /bin/sh
wal -R -n
sxhkd &
setxkbmap se &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
picom --config $HOME/.config/picom/picom.conf --experimental-backends -b &
volumeicon &
bspc monitor DP-2 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6
bspc monitor HDMI-0 -s DP-2


bspc config border_width         2
bspc config window_gap          12


bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

. "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^4' state floating follow=off
bspc rule -a Emacs state=tiled
bspc rule -a spotify desktop='^5'
